# ============================== Filebeat inputs ===============================

filebeat.inputs:
  - type: filestream
    id: r2-gs-endpoint
    enabled: true
    paths:
      - './r2-gs-endpoint/application.log'
    index: "r2gs-log-application-%{+yyyy.MM.ww.DDD}-v1"
    processors:
      #2022-05-29 22:17:29|INFO |ApplicationStartUp:79|-|Application ready post event took: 0 ms
      - dissect:
          tokenizer: "%{timestamp|string}|%{level|string}|%{class|string}|%{requestId|string}|%{text|string}"
          target_prefix: ""


# ============================== Filebeat modules ==============================

# ======================= Elasticsearch template setting =======================
setup.template.enabled: false

# ================================== General ===================================
setup.ilm.enabled: false

#============================== Dashboards =====================================
setup.dashboards:
  enabled: false

# ================================== Outputs ===================================

output.elasticsearch:
  hosts: ["192.168.1.126:9200"]
  allow_older_versions: true


#============================== Kibana =========================================
setup.kibana:
  host: "${KIBANA_HOST}:5601"

# ================================= Global Processors =================================
processors:
  - drop_fields:
      fields: ["agent", "log", "input", "host", "ecs", "message" ]

