version: '3.9'

services:
  r2-gs-es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - node.name=es01
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin='*'
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../services/esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    labels:
      - "co.elastic.logs/enabled: false"
    networks:
      - esnet
  r2-gs-kibana:
    depends_on:
      - r2-gs-es01
    image: docker.elastic.co/kibana/kibana:8.6.2
    volumes:
      - ../services/kibanadata:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://r2-gs-es01:9200
      - http.cors.enabled=true
      - http.cors.allow-origin='*'
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    labels:
      - "co.elastic.logs/enabled: false"
    networks:
      - esnet
networks:
  esnet:
    external: true
